# Generated by Django 5.2.4 on 2025-07-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_alter_studentexerciselog_student"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="knowledgepoint",
            table="exercises_knowledgepoint",
        ),
    ]
