# Generated by Django 5.2.4 on 2025-07-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0003_alter_knowledgepoint_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="answer",
            field=models.JSONField(
                default=dict, help_text="必须包含reference_answer字段"
            ),
        ),
    ]
