# Generated by Django 5.2.4 on 2025-07-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0006_alter_exercisehistory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercisehistory",
            options={"ordering": ["-created_at"]},
        ),
    ]
