# Generated by Django 5.2.4 on 2025-07-13 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0007_alter_exercisehistory_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("textbook", "教材"),
                            ("lecture", "讲义"),
                            ("paper", "论文"),
                            ("example", "案例"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("content", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="studentexerciselog",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="studentexerciselog",
            name="student",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="question",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="average_score",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="weak_knowledge_points",
        ),
        migrations.AddField(
            model_name="exercise",
            name="calculated_difficulty",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="exercise",
            name="common_mistakes",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="exercise",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="feedback_template",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="hints",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="exercise",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mc", "选择题"),
                    ("tf", "判断题"),
                    ("fb", "填空题"),
                    ("code", "编程题"),
                    ("doc", "文档分析题"),
                ],
                default="mc",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="solution_steps",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="exercise",
            name="title",
            field=models.CharField(default="mc", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exercise",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="difficulty_level",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="exercises.knowledgepoint",
            ),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="prerequisite",
            field=models.ManyToManyField(
                blank=True, related_name="required_by", to="exercises.knowledgepoint"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="avg_time_per_question",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="correct_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="knowledge_mastery",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="learning_style",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="preferred_difficulty",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="skill_distribution",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="total_exercises",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="answer",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="exercise",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exercises.document",
            ),
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="related_documents",
            field=models.ManyToManyField(blank=True, to="exercises.document"),
        ),
        migrations.CreateModel(
            name="ExerciseAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_answer", models.JSONField()),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("time_spent", models.PositiveIntegerField(default=0)),
                ("used_hints", models.JSONField(default=list)),
                ("is_correct", models.BooleanField()),
                ("score", models.FloatField(blank=True, null=True)),
                ("partial_scores", models.JSONField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("detailed_feedback", models.JSONField(default=dict)),
                ("ai_feedback", models.TextField(blank=True)),
                ("feedback_rating", models.SmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exercises.exercise",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "练习记录",
                "verbose_name_plural": "练习记录",
                "ordering": ["-created_at"],
                "unique_together": {("student", "exercise", "attempt_number")},
            },
        ),
        migrations.DeleteModel(
            name="ExerciseHistory",
        ),
        migrations.DeleteModel(
            name="StudentExerciseLog",
        ),
    ]
