# Generated by Django 5.2.4 on 2025-07-13 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0008_document_remove_studentexerciselog_exercise_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="related_knowledge_points",
            field=models.ManyToManyField(
                blank=True,
                related_name="documents_related",
                to="exercises.knowledgepoint",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="weak_knowledge_points",
            field=models.ManyToManyField(
                blank=True,
                related_name="weak_for_profiles",
                to="exercises.knowledgepoint",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
