# Generated by Django 5.2.4 on 2025-07-13 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0009_document_related_knowledge_points_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="exerciseattempt",
            old_name="student_answer",
            new_name="student_answer",
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
