# Generated by Django 5.2.4 on 2025-07-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exercises",
            "0010_rename_submitted_answer_exerciseattempt_student_answer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="correct_count",
            field=models.IntegerField(default=0),
        ),
    ]
