# Generated by Django 5.2.4 on 2025-07-14 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0011_studentprofile_correct_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="related_knowledge_points",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="knowledge_points",
            field=models.ManyToManyField(
                related_name="exercises", to="exercises.knowledgepoint"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgepoint",
            name="related_documents",
            field=models.ManyToManyField(
                blank=True, related_name="knowledge_points", to="exercises.document"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="weak_knowledge_points",
            field=models.ManyToManyField(
                blank=True,
                related_name="weak_student_profiles",
                to="exercises.knowledgepoint",
            ),
        ),
        migrations.AlterModelTable(
            name="knowledgepoint",
            table=None,
        ),
    ]
